name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.serverStatus().ok'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run linters
        run: |
          mvn checkstyle:check
          mvn pmd:check
          mvn spotbugs:check

      - name: Build and test with Maven
        run: |
          mvn -B verify --file pom.xml
          mvn jacoco:report
          # Optionally upload coverage to a service like Codecov
          # - name: Upload coverage to Codecov
          #   uses: codecov/codecov-action@v3